name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repostiry
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCERHUB_USERNAME}}
          password: ${{ secrets.DOCERHUB_TOKEN}}

      - name: Build and push Docker image
        run: |
          docker build -t hp4129889/huihui-mahjong:ci-test .
          docker push hp4129889/huihui-mahjong:ci-test